theme: minima
title: Learning Github
author: Grant Didway
email: grant.didway@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The purpose of this site is to learn how to use Github
  pages to easily create a website. There won't be much here
  right now.

# social links
twitter_username: grantdidway # DO NOT include the @ character, or else the build will fail!
github_username:  didwayg # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
